### ISSUE TITLE
Unresponsive

### ISSUE THREAD

**Issue by BenBellborn** [V-ktor/RNG-quest#1]
Hi Viktor,
I love your game, but all my characters will eventually make the game unresponsive.

Shouldn't source main.gd that today contains:
```
func optimize_equipment():
	var i:= 0
	while i<player_inventory.size():
		var item: Dictionary = player_inventory[i]
		if item.has("2h") && item["2h"]:
			if !weapon_2h_alowed:
				continue
		elif !weapon_1h_alowed:
			continue
```

Be changed to:
```
`func optimize_equipment():
	var i:= 0
	while i<player_inventory.size():
		var item: Dictionary = player_inventory[i]
		if item.has("2h") && item["2h"]:
			if !weapon_2h_alowed:
				i += 1
				continue
		elif !weapon_1h_alowed:
			i += 1
			continue
```

I've never coded in Godot so I could be totally wrong, but adding i+=1 to both places would remove the unresponsive game for me atleast. 
BR / Ben

**Comment by V-ktor** [comment]
Yes, you're right.
Thank you for reporting the bug.
