### ISSUE TITLE
Item tooltips hang open

### ISSUE THREAD

**Issue by AlecXanderLynn** [V-ktor/RNG-quest#3]
Item descriptions that open when the mouse is held over the item normally close themselves when this is no longer the case, but if the cursor is held over an item and a second instance of that item is acquired, the tooltip remains open if the mouse is moved elsewhere. This happens with items that are purchased, as well as drops from enemies.
To reproduce:
this is easiest to see while grinding, and getting a second enemie that drops something you already have. Once you have one drop, mouse over the drop you will get, and then move the mouse away once you do.

**Comment by AlecXanderLynn** [comment]
![bug](https://github.com/V-ktor/RNG-quest/assets/15841550/01bb376c-2ea0-4c41-9e78-db47e3d1f15d)
It isn't consistant about when it does or doesn't trigger. Sometimes the above method works, and sometimes it doesn't. The mouse cursor in this image is down and to the right from the velvet bandage tooltip.

**Comment by V-ktor** [comment]
I implemented a custom tooltip with tabs and colour coding.
This should be fixed by that change.
